# Homework 2
Claire Summers

### Question 1

In [78]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [79]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [80]:
%cd /content/drive/MyDrive/EGR270/
%cd practice
!wget https://raw.githubusercontent.com/VSZM/ELTE_Adatbanyaszat_es_Gepi_tanulas/master/practice/fuel_data.txt

/content/drive/MyDrive/EGR270
/content/drive/MyDrive/EGR270/practice
--2026-02-17 20:14:07--  https://raw.githubusercontent.com/VSZM/ELTE_Adatbanyaszat_es_Gepi_tanulas/master/practice/fuel_data.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8222 (8.0K) [text/plain]
Saving to: ‘fuel_data.txt.5’

fuel_data.txt.5     100%[===================>]   8.03K  --.-KB/s    in 0.008s

2026-02-17 20:14:07 (1.02 MB/s) - ‘fuel_data.txt.5’ saved [8222/8222]

In [81]:
import pandas as pd

In [82]:
df = pd.read_csv('fuel_data.txt', delimiter='\t')

### Question 2

In [83]:
df.head(41)

,date,starttime,endtime,starttemp,endtemp,air conditioner,trafic,route,dist,avg.cons.,speed,duration,fuel type,road,num. persons
0,2018.06.03,00:03,01:16,17,15,off,low,bp-dujv,69.8,4.5,57,01:13,95+,standard,1
1,2018.06.03,08:20,09:29,19,24,off,low,dujv-bp,68.6,4.6,59,01:09,95+,standard,2
2,2018.06.03,13:00,15:00,30,28,on,normal,bp-dujv,79.5,6.0,47,01:40,95+,standard,3
3,2018.06.04,15:30,16:30,29,28,on,normal,dujv-szelid,45.2,4.3,56,00:48,95+,standard,1
4,2018.06.04,18:18,19:10,30,25,on,normal,szelid-dujv,47.5,4.7,57,00:49,95+,standard,1
5,2018.06.05,21:04,22:20,25,25,off,normal,bp-dujv,72.9,4.6,56,01:17,95+,standard,1
6,2018.06.07,10:48,11:36,18,24,off,normal,dujv-szfvar,52.9,5.2,58,00:52,95+,standard,1
7,2018.06.07,15:22,16:25,31,26,on,normal,szfvar-dujv,53.3,5.2,50,01:03,95+,standard,1
8,2018.06.08,21:25,22:28,24,22,off,normal,szfvar-dujv,54.4,4.5,51,01:03,95+,standard,1
9,2018.06.10,17:11,18:38,30,24,on,normal,dujv-bp,68.0,4.8,50,01:21,95+,standard,1
10,2018.06.10,20:48,22:05,23,22,off,low,bp-dujv,70.0,4.5,55,01:15,95FS,standard,1
11,2018.06.11,11:11,11:47,25,27,off,low,dujv-ercsi,35.9,4.2,58,00:37,95FS,standard,1
12,2018.06.11,13:32,14:14,29,29,on,low,ercsi-dujv,36.7,4.5,53,00:41,95FS,standard,1
13,2018.06.12,08:50,09:49,29,26,on,normal,dujv-szfvar,52.3,4.7,53,00:58,95FS,standard,1
14,2018.06.12,12:45,13:37,30,30,on,normal,szfvar-dujv,51.8,4.4,53,00:58,95FS,standard,1
15,2018.06.15,11:15,11:45,16,18,off,normal,dujv-dunaegyhaza,21.7,4.4,45,00:29,95FS,standard,1
16,2018.06.15,11:45,13:05,18,22,off,normal,dunaegyhaza-bp,89.1,5.9,77,01:09,95FS,highway,2
17,2018.06.15,17:10,18:15,23,21,on,normal,bp-dujv,72.9,6.0,70,01:02,95FS,highway,2
18,2018.06.20,17:30,18:26,32,28,on,normal,szfvar-dujv,53.2,5.5,58,00:55,95+,standard,1
19,2018.06.21,06:36,07:40,22,23,off,normal,dujv-bp,70.4,4.7,63,01:07,95+,highway,1
20,2018.06.21,18:00,18:56,30,28,on,normal,bp-dujv,66.0,5.0,72,00:54,95+,highway,1
21,2018.06.23,07:45,08:45,11,15,off,normal,dujv-bp,72.1,6.0,74,00:58,95+,highway,2
22,2018.06.23,18:15,19:35,18,17,off,normal,bp-dujv,75.4,5.3,62,01:12,95+,highway,2
23,2018.06.24,14:05,15:17,18,20,off,low,dujv-kkmet,74.4,4.1,61,01:12,95FS,standard,1
24,2018.06.24,15:35,16:51,20,22,on,normal,kkmet-szeged,88.4,5.8,84,01:03,95FS,highway,4
25,2018.06.24,17:25,20:20,25,18,off,traffic jam + normal,szeged-novisad,137.4,5.3,48,02:50,95FS,highway,1
26,2018.06.27,14:20,17:03,17,14,off,normal,novisad-horgos,140.5,5.4,56,02:28,95FS,highway,1
27,2017.06.27,17:03,17:32,14,14,off,traffic jam,horgos-roszke,0.6,18.1,1,00:23,95FS,highway,1
28,2017.06.28,08:25,09:30,16,20,off,normal,dujv-bp,70.3,5.0,67,01:02,95FS,highway,1
29,2017.06.28,16:45,17:56,19,16,off,normal,bp-dujv,71.9,5.1,60,01:11,95FS,highway,1
30,2017.06.29,08:00,09:16,17,18,off,normal,dujv-bp,70.1,5.5,60,01:09,95FS,highway,1
31,2017.06.30,12:25,13:15,26,23,on,normal,dujv-szfvar,51.0,5.6,62,00:48,95FS,standard,1
32,2017.06.30,14:40,15:30,27,27,on,normal,szfvar-veszprem,49.4,5.3,59,00:49,95FS,standard,2
33,2017.06.30,21:16,22:01,14,16,off,low,veszprem-szfvar,48.2,4.3,64,00:45,95FS,standard,2
34,2017.06.30,23:00,00:21,16,12,off,low,szfvar-dujv,64.5,4.6,49,01:19,95FS,standard,1
35,2017.07.02,06:50,08:25,11,17,off,high,dujv-bp,90.1,5.4,59,01:31,95FS,highway,3
36,2017.07.02,17:10,18:15,26,24,on,normal,bp-dujv,72.0,5.2,65,01:05,95FS,highway,1
37,2018.07.04,07:10,08:10,18,20,off,normal,dujv-bp,71.8,6.2,73,00:59,95FS,highway,2
38,2018.07.04,17:30,18:30,28,24,on,normal,bp-dujv,70.4,5.2,69,01:01,95FS,highway,1
39,2018.07.05,08:30,09:40,20,25,off,low,dujv-bp,70.8,4.7,64,01:05,95+,highway,1
40,2018.07.05,16:57,18:05,33,29,on,normal,bp-dujv,72.1,5.6,63,01:08,95+,highway,1

### Question 3

In [84]:
df['tempdiff'] = df['endtemp'] - df['starttemp']

df.loc[df['tempdiff'] == df['tempdiff'].min()]

,date,starttime,endtime,starttemp,endtemp,air conditioner,trafic,route,dist,avg.cons.,speed,duration,fuel type,road,num. persons,tempdiff
86,2018.08.27,17:27,19:19,28,19,on,high,bp-dujv,71.8,6.6,38,01:52,95+,highway,1,-9

### Question 4

In [85]:
df['normalized_route'] = df['route'].apply(lambda x: '-'.join(sorted(x.split('-'))))
df

,date,starttime,endtime,starttemp,endtemp,air conditioner,trafic,route,dist,avg.cons.,speed,duration,fuel type,road,num. persons,tempdiff,normalized_route
0,2018.06.03,00:03,01:16,17,15,off,low,bp-dujv,69.8,4.5,57,01:13,95+,standard,1,-2,bp-dujv
1,2018.06.03,08:20,09:29,19,24,off,low,dujv-bp,68.6,4.6,59,01:09,95+,standard,2,5,bp-dujv
2,2018.06.03,13:00,15:00,30,28,on,normal,bp-dujv,79.5,6.0,47,01:40,95+,standard,3,-2,bp-dujv
3,2018.06.04,15:30,16:30,29,28,on,normal,dujv-szelid,45.2,4.3,56,00:48,95+,standard,1,-1,dujv-szelid
4,2018.06.04,18:18,19:10,30,25,on,normal,szelid-dujv,47.5,4.7,57,00:49,95+,standard,1,-5,dujv-szelid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2018.09.03,22:00,22:55,21,19,off,normal,bp-dujv,68.2,5.3,78,00:52,95+,highway,1,-2,bp-dujv
96,2018.09.04,06:42,07:55,16,17,off,normal,dujv-bp,69.1,4.5,58,01:10,95+,highway,1,1,bp-dujv
97,2018.09.04,20:00,21:10,17,16,off,low,bp-dujv,71.6,4.5,65,01:05,95+,highway,1,-1,bp-dujv
98,2018.09.05,08:15,09:25,15,20,off,normal,dujv-bp,71.7,4.7,62,01:09,95+,highway,1,5,bp-dujv
99,2018.09.05,20:50,21:52,21,19,off,low,bp-dujv,71.6,4.8,73,00:58,95+,highway,1,-2,bp-dujv

### Question 5

In [86]:
df['Destination'] = df['route'].apply(lambda x: x.split('-')[1])
print(df['Destination'].value_counts().idxmax())

dujv

### Question 6

In [87]:
df['avg_duration'] = df['duration'].apply(lambda x: x.split('-')[0])
df

,date,starttime,endtime,starttemp,endtemp,air conditioner,trafic,route,dist,avg.cons.,speed,duration,fuel type,road,num. persons,tempdiff,normalized_route,Destination,avg_duration
0,2018.06.03,00:03,01:16,17,15,off,low,bp-dujv,69.8,4.5,57,01:13,95+,standard,1,-2,bp-dujv,dujv,01:13
1,2018.06.03,08:20,09:29,19,24,off,low,dujv-bp,68.6,4.6,59,01:09,95+,standard,2,5,bp-dujv,bp,01:09
2,2018.06.03,13:00,15:00,30,28,on,normal,bp-dujv,79.5,6.0,47,01:40,95+,standard,3,-2,bp-dujv,dujv,01:40
3,2018.06.04,15:30,16:30,29,28,on,normal,dujv-szelid,45.2,4.3,56,00:48,95+,standard,1,-1,dujv-szelid,szelid,00:48
4,2018.06.04,18:18,19:10,30,25,on,normal,szelid-dujv,47.5,4.7,57,00:49,95+,standard,1,-5,dujv-szelid,dujv,00:49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2018.09.03,22:00,22:55,21,19,off,normal,bp-dujv,68.2,5.3,78,00:52,95+,highway,1,-2,bp-dujv,dujv,00:52
96,2018.09.04,06:42,07:55,16,17,off,normal,dujv-bp,69.1,4.5,58,01:10,95+,highway,1,1,bp-dujv,bp,01:10
97,2018.09.04,20:00,21:10,17,16,off,low,bp-dujv,71.6,4.5,65,01:05,95+,highway,1,-1,bp-dujv,dujv,01:05
98,2018.09.05,08:15,09:25,15,20,off,normal,dujv-bp,71.7,4.7,62,01:09,95+,highway,1,5,bp-dujv,bp,01:09
99,2018.09.05,20:50,21:52,21,19,off,low,bp-dujv,71.6,4.8,73,00:58,95+,highway,1,-2,bp-dujv,dujv,00:58

### Question 7

In [96]:
df['date'] = pd.to_datetime(df['date'], format='%Y.%m.%d')
df['month'] = df['date'].dt.month
highest_speed = df.loc[df['speed'].idxmax()]
month_highest_speed = highest_speed['date'].month

print(month_highest_speed)

8